### PR TITLE
Fix: First Page Appearing on all pages

### PR DESCRIPTION
**Pull request by ib0b**
Image alias leads to only the first image appearing on all pages, since alias has to be unique

### CODE REVIEW

**Comment by patmood** [comment]
@updatesvc thanks for your contribution! How can I reproduce the issue? The resulting pages seem to be correct on https://patmood.github.io/scanned_look/

**Comment by ib0b** [comment]
Sorry for the late reply, 
The actual scan process is ok, but the compiling of the scanned images into a pdf is what has a bug.
You can try with the sample pdf in the repo, I only get the first page when downloaded.
Here is the scanned download : https://file.io/8ZlkPWtRv4bF

**Comment by patmood** [comment]
@updatesvc I see it now - thanks for the contribution! How did you even find this? 😂

**Comment by ib0b** [comment]
> @updatesvc I see it now - thanks for the contribution! How did you even find this? 😂

😂😂😂
Wanted a scanned PDF look, found a lot of paid options that didn't look good.
Found yours too,  great project

**Pull request merged**
